### ISSUE TITLE
Build IM (2 of them)

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR_installation_preparation#8]
#### At least, 2 persons
- [x] Collecting screws & parts
- [x] Mechanical assembly
- [x] Cabling (pico)
- [x] measure its weight  with flags
- [x] assembly (glue) the flags

For IM assembly:  
http://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=3907  
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=5973

**Comment by YoshinoriFujii** [comment]
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VIS/TypeB/Minutes  
> Mark glued ferromagnetic disks on the last 5 IM flags. This completes 2 sets, for SR3 and SRM.
> Hirata-san worked on building two IMs for SR3 and SRM. The SR3 one just needs to have flags attached and to be weighed; the SRM needs another few hours work.

**Comment by Satoshi-Tanioka** [comment]
Almost Completed building IMs.
Unfortunately, one IM flag was got away and Mark glued another one to replace.

**Comment by YoshinoriFujii** [comment]
weight information from [k-log#4733](http://klog.icrr.u-tokyo.ac.jp/osl/?r=4733 "k-log#4733")

| CAD (w/o ballast mass) | IM-1 | IM-2 |
|:---:|:---:|:---:|
| 26.1 kg | 25.8 kg |  |
